lastupdatecheck: 0
recentrepos:
    - /home/sheape/code/dotfiles
    - /home/sheape/code/dogy.backend
    - /home/sheape/code/voidlings
    - /home/sheape/code/dogyapp
    - /opt/void-packages
    - /home/sheape/code/dogy-assistant
    - /home/sheape/code/Sheape
    - /home/sheape/code/onboarding-automation-onenine
    - /home/sheape/code/emacs-conf
    - /home/sheape/code/neetcode
    - /home/sheape/code/fdt
    - /home/sheape/.bin
    - /home/sheape/code/ecg/ecg-website
    - /home/sheape/code/ecg/ecg-model-inference
    - /home/sheape/code/ecg/ecg-taipy
    - /home/sheape/code/ecg/ecg-streamlit
    - /home/sheape/docs/school/grade-12/pr2/research_paper
    - /home/sheape/docs/org/school
    - /opt/texlive/texmf-local/tex/latex/local
    - /home/sheape/code/metamask-bruteforce-v3
    - /home/sheape/docs/org/roam/grade-12
    - /home/sheape/code/acsci-gr12.github.io
    - /home/sheape/code/acsci-gr12.github.io/content
    - /home/sheape/.local/src/hyprland-void
    - /home/sheape/docs/org/roam/personal
    - /home/sheape/code/cartograph-non-free
    - /home/sheape/.local/test/test_folder
    - /home/sheape/.config/emacs
    - /home/sheape/code/rust-practice
    - /home/sheape/.local/src/notify-receive
    - /home/sheape/code/metamask-bruteforce-v2
    - /home/sheape/code/st
    - /home/sheape/code/metamask-bruteforce
    - /home/sheape/code/somedudes_vrej
    - /home/sheape/code/dwm
    - /home/sheape/code/qmk-sweep-keymap
    - /home/sheape/dl/ferris-sweep/Sweepv2.1
startuppopupversion: 5
lastversion: 0.43.1
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
diffcontextsize: 3
renamesimilaritythreshold: 50
localbranchsortorder: recency
remotebranchsortorder: alphabetical
gitlogorder: topo-order
gitlogshowgraph: always
