# ~/.config/starship.toml

[character]
format = "$symbol "
success_symbol = "[](bold blue)"
vicmd_symbol = "[](bold blue)"
error_symbol = "[](bold red) "

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 5
truncation_symbol = "…/"
format = "[$path]($style) [$read_only]($read_only_style)"
read_only = ""

[package]
disabled = true

[time]
time_format = " %l:%M%P"
format = "[$time]($style) "
style = "bold yellow"
disabled = false

# Programming Languages

[nodejs]
format = "via [$symbol $version]($style) "
symbol = ""
style = "bold green"

[python]
format = "via [$symbol $version]($style) "
symbol = ""
style = "bold yellow"

[java]
format = "via [$symbol $version]($style)"
symbol = ""
style = "bold red"

[git_branch]
format = "on [$symbol $branch]($style) "
symbol = ""
style = "bold blue"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
tag_symbol = ""
style = "bold blue"
tag_disabled = false

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
disabled = true
