packages:
  - package: "ImageMagick"
    pkg_name: "ImageMagick"
  - package: "R"
    pkg_name: "R"
  - package: "Android Studio"
    pkg_name: "android-studio"
  - package: "Android tools"
    pkg_name: "android-tools"
  - package: "Adwaita Icon theme"
    pkg_name: "adwaita-icon-theme"
  - package: "Bash" # Just in case zsh fails
    pkg_name: "bash"
  - package: "Bc"
    pkg_name: "bc"
  - package: "Brave Browser"
    pkg_name: "brave-bin"
  - package: "Chafa"
    pkg_name: "chafa"
  - package: "Chafa Devel"
    pkg_name: "chafa-devel"
  - package: "Chrony"
    pkg_name: "chrony"
  - package: "Container Daemon"
    pkg_name: "containerd"
  - package: "Curl"
    pkg_name: "curl"
  - package: "Dash"
    pkg_name: "dash"
  - package: "Dbus"
    pkg_name: "dbus"
  - package: "Dbus Devel"
    pkg_name: "dbus-devel"
  - package: "Dbus Glib"
    pkg_name: "dbus-glib"
  - package: "Dbus Libraries"
    pkg_name: "dbus-libs"
  - package: "Desktop File Utils"
    pkg_name: "desktop-file-utils"
  - package: "Device Mapper"
    pkg_name: "device-mapper"
  - package: "Dhcpcd"
    pkg_name: "dhcpcd"
  - package: "Dragon"
    pkg_name: "dragon"
  - package: "Elogind"
    pkg_name: "elogind"
  - package: "Entr"
    pkg_name: "entr"
  - package: "Encodings"
    pkg_name: "encodings"
  - package: "Ethtool"
    pkg_name: "ethtool"
  - package: "Eza"
    pkg_name: "eza"
  - package: "Fd"
    pkg_name: "fd"
  - package: "FFMPEG"
    pkg_name: "ffmpeg"
  - package: "FFMPEG Thumbnailer"
    pkg_name: "ffmpegthumbnailer"
  - package: "FFPlay"
    pkg_name: "ffplay"
  - package: "File"
    pkg_name: "file"
  - package: "Firefox"
    pkg_name: "firefox"
  - package: "Fzf"
    pkg_name: "fzf"
  - package: "GNUPG"
    pkg_name: "gnupg"
  - package: "Go"
    pkg_name: "go"
  - package: "Gradle"
    pkg_name: "gradle"
  - package: "Grim"
    pkg_name: "grim"
  - package: "Gum"
    pkg_name: "gum"
  - package: "Grep"
    pkg_name: "grep"
  - package: "Git Cliff"
    pkg_name: "git-cliff"
  - package: "Github CLI"
    pkg_name: "github-cli"
  - package: "Hyprland"
    pkg_name: "hyprland"
  - package: "Hyprcursor"
    pkg_name: "hyprcursor"
  - package: "Hyprpaper"
    pkg_name: "hyprpaper"
  - package: "Iputils"
    pkg_name: "iputils"
  - package: "Ipw2100 Firmware"
    pkg_name: "ipw2100-firmware"
  - package: "Ipw2200 Firmware"
    pkg_name: "ipw2200-firmware"
  - package: "Iw"
    pkg_name: "iw"
  - package: "Jq"
    pkg_name: "jq"
  - package: "Kbd"
    pkg_name: "kbd"
  - package: "Keepassxc"
    pkg_name: "keepassxc"
  - package: "Linux Firmware (Intel)"
    pkg_name: "linux-firmware-intel"
  - package: "Linux Firmware (Network)"
    pkg_name: "linux-firmware-network"
  - package: "Linux Firmware (Broadcom)"
    pkg_name: "linux-firmware-broadcom"
  - package: "Lua"
    pkg_name: "lua"
  - package: "Lxappearance"
    pkg_name: "lxappearance"
  - package: "Make"
    pkg_name: "make"
  - package: "Mdcat"
    pkg_name: "mdcat"
  - package: "Mesa"
    pkg_name: "mesa"
  - package: "Mesa DRI"
    pkg_name: "mesa-dri"
  - package: "Mesa Intel DRI"
    pkg_name: "mesa-intel-dri"
  - package: "Mesa OpenCL DRI"
    pkg_name: "mesa-opencl"
  - package: "Mesa Vulkan Intel DRI"
    pkg_name: "mesa-vulkan-intel"
  - package: "Mesa Vulkan Intel DRI"
    pkg_name: "mesa-vulkan-intel"
  - package: "Mimetypes"
    pkg_name: "mime-types"
  - package: "Mpd"
    pkg_name: "mpd"
  - package: "Ncdu"
    pkg_name: "ncdu"
  - package: "Ncurses"
    pkg_name: "ncurses"
  - package: "Ncurses Base"
    pkg_name: "ncurses-base"
  - package: "Network Manager"
    pkg_name: "NetworkManager"
  - package: "Neovide"
    pkg_name: "neovide"
  - package: "Neovim"
    pkg_name: "neovim"
  - package: "Nodejs"
    pkg_name: "nodejs"
  - package: "Nsxiv"
    pkg_name: "nsxiv"
  - package: "Opendoas"
    pkg_name: "opendoas"
  - package: "OpenJDK 17"
    pkg_name: "openjdk17"
  - package: "OpenJDK 17 Runtime"
    pkg_name: "openjdk17-jre"
  - package: "OpenSSH"
    pkg_name: "openssh"
  - package: "OpenSSL"
    pkg_name: "openssl"
  - package: "OS Prober"
    pkg_name: "os-prober"
  - package: "Pam"
    pkg_name: "pam"
  - package: "Pam Base"
    pkg_name: "pam-base"
  - package: "Pam Libs"
    pkg_name: "pam-libs"
  - package: "Patch"
    pkg_name: "patch"
  - package: "Pcmanfm"
    pkg_name: "pcmanfm"
  - package: "Perl"
    pkg_name: "perl"
  - package: "Pkg config"
    pkg_name: "pkg-config"
  - package: "Playerctl"
    pkg_name: "playerctl"
  - package: "Pnpm"
    pkg_name: "pnpm"
  - package: "Polkit"
    pkg_name: "polkit"
  - package: "Poppler"
    pkg_name: "poppler"
  - package: "Poppler Utils"
    pkg_name: "poppler-utils"
  - package: "Process monitor"
    pkg_name: "procps-ng"
  - package: "Pyright"
    pkg_name: "pyright"
  - package: "Python 3"
    pkg_name: "python3"
  - package: "Pip"
    pkg_name: "python3-pip"
  - package: "Pipx"
    pkg_name: "python3-pipx"
  - package: "Python 3 Setup tools"
    pkg_name: "python3-setuptools"
  - package: "Python Watchdog"
    pkg_name: "python3-watchdog"
  - package: "Qt5ct"
    pkg_name: "qt5ct"
  - package: "Qt6ct"
    pkg_name: "qt6ct"
  - package: "Qt chooser"
    pkg_name: "qtchooser"
  - package: "Qutebrowser Profile"
    pkg_name: "qutebrowser-profile"
  - package: "Rakudo"
    pkg_name: "rakudo"
  - package: "Rclone"
    pkg_name: "rclone"
  - package: "Ripgrep"
    pkg_name: "ripgrep"
  - package: "Rsync"
    pkg_name: "rsync"
  - package: "Screen"
    pkg_name: "screen"
  - package: "Sed"
    pkg_name: "sed"
  - package: "Setxkbmap"
    pkg_name: "setxkbmap"
  - package: "Shadow"
    pkg_name: "shadow"
  - package: "Shared Mime info"
    pkg_name: "shared-mime-info"
  - package: "Shellcheck"
    pkg_name: "shellcheck"
  - package: "Slop"
    pkg_name: "slop"
  - package: "Slurp"
    pkg_name: "slurp"
  - package: "Socat"
    pkg_name: "socat"
  - package: "Sudo"
    pkg_name: "sudo"
  - package: "Tealdeer"
    pkg_name: "tealdeer"
  - package: "Tmux"
    pkg_name: "tmux"
  - package: "Typst"
    pkg_name: "typst"
  - package: "Timezone data"
    pkg_name: "tzdata"
  - package: "USB Utils"
    pkg_name: "usbutils"
  - package: "Unicode Emoji"
    pkg_name: "unicode-emoji"
  - package: "Vim"
    pkg_name: "vim"
  - package: "Void Multilib"
    pkg_name: "void-repo-multilib"
  - package: "Void Multilib Nonfree"
    pkg_name: "void-repo-multilib-nonfree"
  - package: "Void Nonfree"
    pkg_name: "void-repo-nonfree"
  - package: "Void Nonfree"
    pkg_name: "void-repo-nonfree"
  - package: "Vivid"
    pkg_name: "vivid"
  - package: "Wayland"
    pkg_name: "wayland"
  - package: "Wayland Devel"
    pkg_name: "wayland-devel"
  - package: "Wayland Protocol"
    pkg_name: "wayland-protocols"
  - package: "Wev"
    pkg_name: "wev"
  - package: "Wget"
    pkg_name: "wget"
  - package: "Which"
    pkg_name: "which"
  - package: "Wifi firmware"
    pkg_name: "wifi-firmware"
  - package: "Wireplumber"
    pkg_name: "wireplumber"
  - package: "Wireplumber Elogind"
    pkg_name: "wireplumber-elogind"
  - package: "Wayland Clipboard"
    pkg_name: "wl-clipboard"
  - package: "Wofi"
    pkg_name: "wofi"
  - package: "Wpa Supplicant"
    pkg_name: "wpa_supplicant"
  - package: "XDG Dbus Proxy"
    pkg_name: "xdg-dbus-proxy"
  - package: "XDG Desktop Portal"
    pkg_name: "xdg-desktop-portal"
  - package: "XDG Desktop Portal Hyprland"
    pkg_name: "xdg-desktop-portal-hyprland"
  - package: "XDG Utils"
    pkg_name: "xdg-utils"
  - package: "Xtools"
    pkg_name: "xtools"
  - package: "Xtools minimal"
    pkg_name: "xtools-minimal"
  - package: "Ytdlp"
    pkg_name: "yt-dlp"
  - package: "Ytmdl"
    pkg_name: "ytmdl"
  - package: "Z3"
    pkg_name: "z3"
  - package: "Zathura mupdf"
    pkg_name: "zathura-pdf-mupdf"
