category: "C/C++ Dependencies"
packages:
  - package: "Binutils"
    pkg_name: "binutils"
  - package: "Binutils Doc"
    pkg_name: "binutils-doc"
  - package: "Binutils Libraries"
    pkg_name: "binutils-libs"
  - package: "Bison"
    pkg_name: "bison"
  - package: "Clang"
    pkg_name: "clang"
  - package: "Cmake"
    pkg_name: "cmake"
  - package: "Gcc"
    pkg_name: "gcc"
  - package: "LLDB"
    pkg_name: "lldb"
  - package: "Meson"
    pkg_name: "meson"
  - package: "Ninja"
    pkg_name: "ninja"
