packages:
  - package: "Abook"
    pkg_name: "abook"
  - package: "Btop"
    pkg_name: "btop"
  - package: "Cava"
    pkg_name: "cava"
  - package: "Dunst"
    pkg_name: "dunst"
  - package: "Eww"
    pkg_name: "eww"
  - package: "Foot"
    pkg_name: "foot"
  - package: "Glow"
    pkg_name: "glow"
  - package: "Groff"
    pkg_name: "groff"
  - package: "Lazydocker"
    pkg_name: "lazydocker"
  - package: "Lazygit"
    pkg_name: "lazygit"
  - package: "Less"
    pkg_name: "less"
  - package: "Lf"
    pkg_name: "lf"
  - package: "Mpv"
    pkg_name: "mpv"
  - package: "Neofetch"
    pkg_name: "neofetch"
  - package: "Nushell"
    pkg_name: "nushell"
  - package: "Qutebrowser"
    pkg_name: "qutebrowser"
  - package: "Sc-im"
    pkg_name: "sc-im"
  - package: "Starship"
    pkg_name: "starship"
  - package: "Wofi"
    pkg_name: "wofi"
  - package: "Xdg Desktop Portal Hyprland"
    pkg_name: "xdg-desktop-portal-hyprland"
  - package: "Zathura"
    pkg_name: "zathura"
  - package: "Zsh"
    pkg_name: "zsh"
