---
- name: "{{ category }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}-package.yml"
  register: distribution_config

- name: "{{ category }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}-package.yml"
  when: distribution_config.stat.exists
  loop: "{{ packages }}"
  loop_control:
    loop_var: pkg

- name: "{{ category }} | Checking for Workman Keyboard Layout (X11)"
  ansible.builtin.stat:
    path: "/usr/share/X11/xkb/symbols/workman"
  register: workman_config

- name: "{{ category }} | Checking for Workman Keyboard Layout (loadkeys)"
  ansible.builtin.stat:
    path: "/usr/share/kbd/keymaps/i386/qwerty/us-workman.kmap"
  register: workman_loadkeys_config

- name: "{{ category }} | Checking for Hyprland-Void repository"
  ansible.builtin.stat:
    path: "/etc/xbps.d/hyprland-void.conf"
  register: hyprland_config

- name: "{{ category }} | Checking for Local repository"
  ansible.builtin.stat:
    path: "/etc/xbps.d/local-repo.conf"
  register: local_config

- name: "{{ category }} | Checking for Voidlings repository"
  ansible.builtin.stat:
    path: "/etc/xbps.d/voidlings.conf"
  register: voidlings_config

- name: "{{ category }} | Deploying Hyprland Void Repository"
  become: true
  ansible.builtin.copy:
    src: "hyprland-void.conf"
    dest: "/etc/xbps.d/hyprland-void.conf"
    owner: root
    group: root
    mode: "0644"
  when: not hyprland_config.stat.exists

- name: "{{ category }} | Deploying Local Repository"
  become: true
  ansible.builtin.copy:
    src: "local-repo.conf"
    dest: "/etc/xbps.d/local-repo.conf"
    owner: root
    group: root
    mode: "0644"
  when: not local_config.stat.exists

- name: "{{ category }} | Deploying Voidlings Repository"
  become: true
  ansible.builtin.template:
    src: "voidlings.conf.j2"
    dest: "/etc/xbps.d/voidlings.conf"
    owner: root
    group: root
    mode: "0644"
    force: true
  when: not voidlings_config.stat.exists

- name: "{{ category }} | Syncing Repositories"
  become: true
  ansible.builtin.shell: "xbps-install -Sy"

- name: " {{ category }} | Creating Dir for workman layout (X11)"
  become: true
  ansible.builtin.file:
    path: "/usr/share/X11/xkb/symbols"
    state: directory
    mode: 0755
    owner: root
    group: root
  when: not workman_config.stat.exists

- name: "{{ category }} | Deploying Workman Layout (X11)"
  become: true
  ansible.builtin.copy:
    src: "workman"
    dest: "/usr/share/X11/xkb/symbols/workman"
    owner: root
    group: root
    mode: "0644"
  when: not workman_config.stat.exists

- name: "{{ category }} | Deploying Workman Layout (loadkeys)"
  become: true
  ansible.builtin.copy:
    src: "us-workman.kmap"
    dest: "/usr/share/kbd/keymaps/i386/qwerty/us-workman.kmap"
    owner: root
    group: root
    mode: "0644"
  when: not workman_loadkeys_config.stat.exists

- name: "{{ category }} | Enabling Workman Layout (loadkeys)"
  become: true
  ansible.builtin.shell: "loadkeys /usr/share/kbd/keymaps/i386/qwerty/us-workman.kmap"
