## Uncomment this line if you are using the default qwerty layout
## located in /usr/share/X11/xkb/symbols/us
#setxkbmap -layout us && xset r rate 300 50

## Uncomment this line if you are using the default official workman
## layout located in /usr/share/X11/xkb/symbols/us
#setxkbmap -layout us -variant workman && xset r rate 300 50

## Use this command if you installed workman-git from AUR repo or
## modified your own workman layout. Located in /usr/share/X11/xkb/symbols/workman
#setxkbmap -layout workman && xset r rate 300 50

## Use this command if you installed workman-git from AUR repo or modified your
## own workman layout with mouse keys feature enabled. Located in /usr/share/X11/xkb/symbols/workman
setxkbmap -layout workman -option keypad:pointerkeys && xset r rate 300 50 &

# Choose your window manager or desktop environment here.
#exec qtile
while type dwm >/dev/null ; do dwm && continue || break ; done

exec dwm
