---
- name: "{{ category }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}-package.yml"
  register: distribution_config

- name: "{{ category }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}-package.yml"
  when: distribution_config.stat.exists
  loop: "{{ packages }}"
  loop_control:
    loop_var: pkg

- name: "{{ category }} | Run Tasks: System-wide Config "
  ansible.builtin.include_tasks: "etc-zsh.yml"
  loop:
    - zprofile
    - zshenv

- name: "{{ category }} | Deploying Zsh Plugins"
  become: true
  ansible.builtin.copy:
    src: "plugins"
    dest: "/usr/share/zsh/"
    owner: root
    group: root
    mode: "0755"
    directory_mode: "0755"
