theme:
  lightTheme: false
  activeBorderColor:
    - "#a6e3a1" # Green
    - bold
  inactiveBorderColor:
    - "#cdd6f4" # Text
  optionsTextColor:
    - "#89b4fa" # Blue
  selectedLineBgColor:
    - "#313244" # Surface0
  selectedRangeBgColor:
    - "#313244" # Surface0
  cherryPickedCommitBgColor:
    - "#94e2d5" # Teal
  cherryPickedCommitFgColor:
    - "#89b4fa" # Blue
  unstagedChangesColor:
    - red       # Red
keybinding:
  universal:
    prevItem-alt: 'e'
    nextItem-alt: 'n'
    scrollLeft: 'Y'
    scrollRight: 'O'
    prevBlock-alt: 'y'
    nextBlock-alt: 'o'
    nextMatch: 'k'
    prevMatch: 'K'
    edit: 'E'
    openFile: 'l'
