category: "Fonts"
packages:
  - package: "Cantarell Font"
    pkg_name: "cantarell-fonts"
  - package: "Dejavu Font"
    pkg_name: "dejavu-fonts-ttf"
  - package: "Xorg Fonts"
    pkg_name: "xorg-fonts"
  - package: "Lexend Font"
    pkg_name: "font-lexend"
  - package: "Quicksand Font"
    pkg_name: "font-quicksand"
  - package: "Google Noto Emoji"
    pkg_name: "noto-fonts-emoji"
  - package: "Comfortaa Font"
    pkg_name: "font-comfortaa"
  - package: "Microsoft Core Fonts"
    pkg_name: "msttcorefonts"
  - package: "Font Config"
    pkg_name: "fontconfig"
  - package: "Cartograph Font"
    pkg_name: "font-cartograph-nonfree"
