category: "Gtk/Gnome Utils"
packages:
  - package: "GDK Pixbuf"
    pkg_name: "gdk-pixbuf"
  - package: "Gmime"
    pkg_name: "gmime"
  - package: "Gnome Themes Extra"
    pkg_name: "gnome-themes-extra"
  - package: "Gsettings"
    pkg_name: "gsettings-desktop-schemas"
  - package: "GTK+ v3"
    pkg_name: "gtk+3"
  - package: "GTK Layer"
    pkg_name: "gtk-layer-shell"
  - package: "GTK Icon cache"
    pkg_name: "gtk-update-icon-cache"
  - package: "GTK 4"
    pkg_name: "gtk4"
  - package: "GTK 4 Icon cache"
    pkg_name: "gtk4-update-icon-cache"
  - package: "GTK Source view"
    pkg_name: "gtksourceview4"
