# ~/.config/starship/starship.toml
palette = "catppuccin_mocha"

[line_break]
disabled = true

[character]
format = "$symbol "
success_symbol = "[](bold blue)"
vicmd_symbol = "[](bold blue)"
error_symbol = "[](bold red) "

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style) "

[directory]
truncation_length = 5
truncation_symbol = "…/"
format = "[$path]($style) [$read_only]($read_only_style)"
read_only = " "

[package]
disabled = true

[time]
disabled = true

# Programming Languages

[nodejs]
disabled = true

[python]
format = "via [$symbol $version]($style) "
symbol = ""
style = "bold yellow"

[java]
format = "via [$symbol $version]($style)"
symbol = ""
style = "bold red"

[git_branch]
format = "on [$symbol $branch]($style) "
symbol = ""
style = "bold blue"

[git_commit]
disabled = true

[git_status]
staged = "⇡ $count"
modified = "✏  $count "
untracked = "∗ $count "
style = "bold green"
disabled = false

[gcloud]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
