category: "Filesystem/Compression"
packages:
  - package: "Btrfs Utils"
    pkg_name: "btrfs-progs"
  - package: "Bzip2"
    pkg_name: "bzip2"
  - package: "Bzip Devel"
    pkg_name: "bzip2-devel"
  - package: "Ext4 Utils"
    pkg_name: "e2fsprogs"
  - package: "Ext4 Library Utils"
    pkg_name: "e2fsprogs-libs"
  - package: "F2FS"
    pkg_name: "f2fs-tools"
  - package: "Gzip"
    pkg_name: "gzip"
  - package: "Lzo"
    pkg_name: "lzo"
  - package: "Unzip"
    pkg_name: "unzip"
  - package: "XZ"
    pkg_name: "xz"
  - package: "Zip"
    pkg_name: "zip"
