# Void Package setup
- name: "{{ category }} | {{ pkg.package }} | {{ ansible_distribution }} | Check for Installation"
  ansible.builtin.shell:
    cmd: "xbps-query -s {{ pkg.pkg_name }} | awk '$2 ~ /^{{ pkg.pkg_name }}-[0-9]/ {print $0}'"
  register: package_check
  failed_when: false
  changed_when: false

- name: "{{ category }} | {{ pkg.package }} | {{ ansible_distribution }} | Install"
  become: true
  community.general.xbps:
    name: "{{ pkg.pkg_name }}"
    state: present
  when: package_check.stdout == ""

- name: "{{ category }} | {{ ansible_distribution }} | Checking for Nerd Fonts"
  ansible.builtin.stat:
    path: "/usr/share/fonts/nerd-fonts"
  register: nerd_dir

- name: "{{ category }} | {{ ansible_distribution }} | Install Nerd Fonts"
  become: true
  ansible.builtin.copy:
    src: "nerd-fonts"
    dest: "/usr/share/fonts/"
    mode: "0644"
    directory_mode: "0755"
    force: true
  when: not nerd_dir.stat.exists

- name: "{{ category }} | {{ ansible_distribution }} | Copy all JetBrains fonts to /usr/share/fonts/TTF"
  become: true
  ansible.builtin.find:
    paths: "{{ role_path }}/files/jetbrains-mono"
    patterns: "*.ttf"
  register: ttf_files

- name: "{{ category }} | {{ ansible_distribution }} | Deploying JetBrains fonts to /usr/share/fonts/TTF"
  become: true
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: /usr/share/fonts/TTF/
    owner: root
    group: root
    mode: "0644"
  loop: "{{ ttf_files.files }}"
